default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mvpnextfrotas_development
  username: <%= ENV['DB_USERNAME'] || "nextfrotas" %>
  password: <%= ENV['DB_PASSWORD'] || "nextfrotas123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

test:
  <<: *default
  database: mvpnextfrotas_test
  username: <%= ENV['DB_USERNAME'] || "nextfrotas" %>
  password: <%= ENV['DB_PASSWORD'] || "nextfrotas123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "mvpnextfrotas_production" %>
  username: <%= ENV['DB_USERNAME'] || "nextfrotas" %>
  password: <%= ENV['DB_PASSWORD'] || "nextfrotas123" %>
  host: <%= ENV['DB_HOST'] || "db" %>
